/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all binders
         * @description Returns the complete initial binder-summary collection (no pagination), sorted by updatedAt descending and then by binder UUID ascending for deterministic ordering.
         */
        get: operations["listBinders"];
        put?: never;
        /** Create a new binder */
        post: operations["createBinder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * Get one binder's details
         * @description Returns binder details for the shared binder context (story 7) and the Edit Details tab.
         */
        get: operations["getBinder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a binder's details
         * @description Applies a partial update to the documented dirty fields (story 7 covers name/width/height/pages; later stories add notes, preview page, dimension, and lock-state fields).
         */
        patch: operations["updateBinder"];
        trace?: never;
    };
    "/binders/{binderId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * List a binder's cards
         * @description Returns every binder-owned card, placed and unplaced, without image bytes (story 11).
         */
        get: operations["listBinderCards"];
        put?: never;
        /**
         * Assign a TCGdex card to a binder slot
         * @description Creates a binder-owned card from a normalized TCGdex catalog result and its target placement (story 11). The backend assigns the `tcgdex` source, downloads and installs the card's image, and validates placement against the binder's current dimensions.
         */
        post: operations["createBinderCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the TCGdex card catalog
         * @description Searches TCGdex through the backend (story 11) and returns normalized catalog cards in the provider's original order, without application-level pagination or truncation. Story 41 adds the optional `language` parameter and, for `language=ja`, an automatic English-to-Japanese Pokémon species name translation applied to `query` before searching TCGdex.
         */
        get: operations["searchCardCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        /**
         * Stream a card's image
         * @description Resolves the card's shared image asset and streams its local file with the detected image Content-Type and long-lived immutable caching (story 11). Storage IDs and filenames are never exposed.
         */
        get: operations["getCardImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}/art": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * List a binder's multi-slot art
         * @description Returns every binder-owned multi-slot-art record, placed and unplaced, without image bytes. Art creation does not exist yet (story 25), so this always returns an empty array today.
         */
        get: operations["listBinderArt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** @constant */
            database: "connected";
        };
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
        } & {
            [key: string]: unknown;
        };
        CreateBinderRequest: {
            /** @description Trimmed on the backend; case-insensitive uniqueness is enforced there. */
            name: string;
            /** @description Number of slot columns per binder side. */
            width: number;
            /** @description Number of slot rows per binder side. */
            height: number;
            /** @description Stored binder-page count. Physical pages range from 1 through 2 * pages. */
            pages: number;
        };
        /** @description A partial update; only supplied fields are changed. Story 7 covers name/width/height/pages; later stories (20-24) add notes, preview page, dimension, and lock-state fields to this same request schema. */
        UpdateBinderRequest: {
            /** @description Trimmed on the backend; case-insensitive uniqueness is enforced there. */
            name?: string;
            /** @description Number of slot columns per binder side. */
            width?: number;
            /** @description Number of slot rows per binder side. */
            height?: number;
            /** @description Stored binder-page count. Physical pages range from 1 through 2 * pages. */
            pages?: number;
        };
        Binder: {
            /** Format: uuid */
            id: string;
            name: string;
            width: number;
            height: number;
            pages: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description The lightweight binder representation used by the home-page binder list (story 5). Later stories (20, 22) extend this schema with only the additional preview and completion-metric data those features require, rather than the complete card and multi-slot-art graph. */
        BinderSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            width: number;
            height: number;
            pages: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description One-based physical page, row, and column. All three are populated for a placed item and all three are null for an unplaced item (story 11's slot assignment always supplies all three). */
        PlacementCoordinates: {
            physicalPage: number | null;
            row: number | null;
            column: number | null;
        };
        /** @description A normalized TCGdex catalog card (story 11), returned by `GET /card-catalog/search` and submitted as-is (plus variation and placement) to create a TCGdex-sourced binder card. */
        TcgDexCatalogCard: {
            name: string;
            setName: string | null;
            localNumber: string | null;
            providerCardId: string;
            providerSetId: string;
            /**
             * Format: uri
             * @description The provider's image location; not the frontend-facing image URL.
             */
            imageUrl: string;
        };
        /**
         * @description Which TCGdex-language dataset a card-catalog search targets (story 41).
         * @enum {string}
         */
        CardSearchLanguage: "en" | "ja";
        /** @description `GET /card-catalog/search`'s response body (story 41). Wraps the normalized results with a nonblocking translation-warning flag instead of returning a bare array, so an unsuccessful English-to-Japanese translation attempt can be surfaced without an error response. */
        CardSearchResponse: {
            results: components["schemas"]["TcgDexCatalogCard"][];
            /** @description True only when `language=ja` and `query` looked like an English Pokémon species name attempt but no matching translation was found, so TCGdex was searched using the original entered query instead. */
            translationWarning: boolean;
        };
        /** @description Creates a TCGdex-sourced binder card (story 11). The backend does not refetch card details before saving; it assigns `source` server-side and downloads the image from `imageUrl` itself. */
        CreateCardRequest: {
            name: string;
            setName: string | null;
            localNumber: string | null;
            providerCardId: string;
            providerSetId: string;
            /** Format: uri */
            imageUrl: string;
            variation?: string | null;
            placement: components["schemas"]["PlacementCoordinates"];
        };
        /** @description The complete persisted representation of a binder-owned card. */
        Card: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            binderId: string;
            name: string;
            setName: string | null;
            localNumber: string | null;
            /** @enum {string} */
            source: "tcgdex" | "custom";
            providerCardId: string | null;
            providerSetId: string | null;
            variation: string | null;
            placement: components["schemas"]["PlacementCoordinates"];
            /**
             * Format: uri-reference
             * @description The backend's own `/cards/{cardId}/image` endpoint URL.
             */
            imageUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: {
        binderId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and database are available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The database is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder-summary collection in its documented sort order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinderSummary"][];
                };
            };
        };
    };
    createBinder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBinderRequest"];
            };
        };
        responses: {
            /** @description The binder was created. */
            201: {
                headers: {
                    /** @description The path of the newly created binder resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The request body did not match the documented schema. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A binder with the same case-insensitively normalized name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getBinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateBinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBinderRequest"];
            };
        };
        responses: {
            /** @description The complete persisted binder after applying the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, or the request body did not match the documented schema. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A binder with the same case-insensitively normalized name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinderCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder's cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createBinderCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
            };
        };
        responses: {
            /** @description The card was created and placed. */
            201: {
                headers: {
                    /** @description The path of the newly created card resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, or the request body did not match the documented schema or a valid placement within the binder's current dimensions. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The target placement is already occupied by another card. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex image download failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex image download timed out. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    searchCardCatalog: {
        parameters: {
            query: {
                query: string;
                /** @description Defaults to `en` when omitted. For `ja`, the backend first attempts to translate `query` as an English Pokémon species name (see `CardSearchResponse.translationWarning`). */
                language?: components["schemas"]["CardSearchLanguage"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The normalized TCGdex search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSearchResponse"];
                };
            };
            /** @description The query is missing, or its trimmed length is below the configured minimum. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex search failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex search timed out. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCardImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The card's image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description The cardId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No card, image-asset record, or local file exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinderArt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder's multi-slot art. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
