/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all binders
         * @description Returns the complete initial binder-summary collection (no pagination), sorted by updatedAt descending and then by binder UUID ascending for deterministic ordering.
         */
        get: operations["listBinders"];
        put?: never;
        /** Create a new binder */
        post: operations["createBinder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * Get one binder's details
         * @description Returns binder details for the shared binder context (story 7) and the Edit Details tab.
         */
        get: operations["getBinder"];
        put?: never;
        post?: never;
        /**
         * Permanently delete a binder
         * @description Permanently deletes the binder identified by its UUID, along with every binder-owned card, multi-slot-art, and dependent record, in one database transaction (story 21). Deleting an already-absent binder also returns `204 No Content`. Image assets shared with other binders remain intact; an image asset is cleaned up only after its final card or art reference is removed, and filesystem cleanup runs after the transaction commits - a file-deletion failure does not roll back the committed deletion.
         */
        delete: operations["deleteBinder"];
        options?: never;
        head?: never;
        /**
         * Update a binder's details
         * @description Applies a partial update to the documented dirty fields (story 7 covers name/width/height/pages; later stories add notes, preview page, dimension, and lock-state fields).
         */
        patch: operations["updateBinder"];
        trace?: never;
    };
    "/binders/{binderId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate a binder and every record it owns
         * @description Reads and deep-copies the authoritative binder graph - the binder itself plus every owned card, multi-slot-art, and dependent record - in one database transaction (story 21). Copied records reference the source records' existing immutable image assets rather than copying image files. The backend names the copy by trying the source name plus " Copy", then " Copy 2", " Copy 3", and increasing integers until the case-insensitively normalized name is unique, truncating the source-name portion as needed to fit the 100- character binder-name limit. Requires a client-generated `Idempotency-Key` header; retrying the same key replays the original response instead of creating a second copy, for the shared 24-hour mutation-idempotency retention period.
         */
        post: operations["duplicateBinder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}/exports/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export a binder's layout as a PDF
         * @description Generates a print-ready PDF of the binder's complete layout (story 29) from one transactionally consistent snapshot of the persisted binder, card, art, transform, and style data - never from the browser's own DOM/context. Each displayed spread (the first/last single-sided page, and every intermediate left-right spread) renders as one US Letter landscape PDF page, proportionally scaled to fit within a 0.25-inch margin. The backend finishes generation in a request-scoped temporary file before sending response headers, then streams the completed file; a missing, unreadable, or unsupported local image fails the complete export with Problem Details rather than omitting the item or generating a partial file. Binder lock state never restricts this read-only endpoint.
         */
        post: operations["exportBinderLayoutPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}/exports/art-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export selected placed multi-slot art as a print-ready PDF
         * @description Generates a print-ready PDF containing only the submitted, currently placed multi-slot art (story 30) from one transactionally consistent snapshot of the persisted binder and art data, packed across as many US Letter landscape pages as needed by a documented deterministic rectangle-packing heuristic - never a fixed one-page-per-spread layout, and never including any card. A piece of art too large to fit one page in either orientation is tiled across multiple pages with a fixed physical overlap between adjacent tiles; tiled pages add no assembly text (no titles, tile numbers, or row/column labels). The backend finishes generation in a request-scoped temporary file before sending response headers, then streams the completed file; a missing, unreadable, or unsupported local image fails the complete export with Problem Details rather than omitting the item or generating a partial file. Binder lock state never restricts this read-only endpoint.
         */
        post: operations["exportArtPrintPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * List a binder's cards
         * @description Returns every binder-owned card, placed and unplaced, without image bytes (story 11).
         */
        get: operations["listBinderCards"];
        put?: never;
        /**
         * Assign a TCGdex or custom card to a binder slot or the unplaced-cards section
         * @description Creates a binder-owned card from either a normalized TCGdex catalog result (story 11, `application/json`) or a manually-entered custom card (story 12, `multipart/form-data`) and its target placement, or with a fully-null placement to add it to the unplaced-cards section instead (story 15). The backend assigns the `source` server-side, installs the card's image, and validates a fully-populated placement against the binder's current dimensions.
         */
        post: operations["createBinderCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/card-catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the TCGdex card catalog
         * @description Searches TCGdex through the backend (story 11) and returns normalized catalog cards in the provider's original order, without application-level pagination or truncation. Story 41 adds the optional `language` parameter and, for `language=ja`, an automatic English-to-Japanese Pokémon species name translation applied to `query` before searching TCGdex. Story 41 also adds the optional `includeTcgPocket` parameter, which defaults to `false` (Pokémon TCG Pocket cards are excluded from results unless explicitly requested).
         */
        get: operations["searchCardCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["cardId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Permanently delete a binder-owned card
         * @description Permanently deletes the binder-owned card identified by its UUID (story 13). Deleting an already-absent card also returns `204 No Content`. Card-owned dependent records cascade-delete with the card in the same database transaction. If this removes the final card reference to its image asset, the backend also deletes the image-asset record and local file in that transaction; a failure to delete the now-orphaned local file does not roll back the committed deletion.
         */
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        /**
         * Move/swap one or two cards' binder positions, or update a card's variation
         * @description Either applies a simple move (one update) or a swap (two updates) of card placement coordinates in one database transaction (story 14), or updates the path card's `variation` field (story 16) - the request body's shape determines which. For a move/swap, the path `cardId` must identify the dragged card included among `updates`. Each update supplies the affected card's currently expected placement plus its final placement; the backend compares every expected placement against the persisted row before applying any change, so a stale client never silently overwrites a position another request already changed. A destination occupied by a card not included in `updates` is rejected as a conflict rather than applied. Nullable placement triples are accepted (story 15's unplaced-cards section) alongside populated ones. For a variation update, the trimmed value replaces the card's existing variation using last-write-wins semantics (no expected prior value or timestamp is compared).
         */
        patch: operations["updateCard"];
        trace?: never;
    };
    "/cards/{cardId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["cardId"];
            };
            cookie?: never;
        };
        /**
         * Stream a card's image
         * @description Resolves the card's shared image asset and streams its local file with the detected image Content-Type and long-lived immutable caching (story 11). Storage IDs and filenames are never exposed.
         */
        get: operations["getCardImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/binders/{binderId}/art": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        /**
         * List a binder's multi-slot art
         * @description Returns every binder-owned multi-slot-art record, placed and unplaced, without image bytes (story 25). Placement is always null today - placing art on the layout is story 26's scope.
         */
        get: operations["listBinderArt"];
        put?: never;
        /**
         * Create multi-slot art in the unplaced-art section
         * @description Creates binder-owned multi-slot art from one multipart request containing the image and normalized art metadata (story 25). New art always starts unplaced (all-null placement); placing it on the layout is story 26's scope.
         */
        post: operations["createBinderArt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/art/{artId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Permanently delete a binder-owned multi-slot art item
         * @description Permanently deletes the binder-owned art item identified by its UUID (story 26). Deleting an already-absent art item also returns `204 No Content`. If this removes the final art reference to its image asset, the backend also deletes the image-asset record and its local file(s); a failure to delete the now-orphaned local file(s) does not roll back the committed deletion.
         */
        delete: operations["deleteArt"];
        options?: never;
        head?: never;
        /**
         * Move or edit one multi-slot art item
         * @description Applies either a placement move or a metadata/image edit to one art item (story 26), branching on the request's content type. An `application/json` body moves the art to a new placement (or to the unplaced-art section) using the same expected/final compare-before-write pattern as `PATCH /cards/{cardId}`; art never swaps, so exactly one placement pair is supplied. A `multipart/form-data` body edits the art's own title, description, dimensions, positioning/scaling/rotation, and style overrides, and may optionally replace its image; if edited dimensions would leave currently-placed art out of bounds or overlapping another item, the request is rejected with `409 Conflict` unless `moveToUnplacedOnConflict` is `true`, in which case the art is saved and moved to the unplaced-art section in the same request.
         */
        patch: operations["updateArt"];
        trace?: never;
    };
    "/art/{artId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Duplicate a multi-slot art item into the unplaced-art section
         * @description Creates a new, always-unplaced art item sharing the source item's image asset and every editable property (story 26). Requires a client-generated `Idempotency-Key` header; retrying the same key replays the original response instead of creating a second copy, for the shared 24-hour mutation-idempotency retention period.
         */
        post: operations["duplicateArt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/art/{artId}/image": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        /**
         * Stream a multi-slot art item's rendering image
         * @description Resolves the art's shared image asset and streams its orientation-normalized local file with the detected image Content-Type and long-lived immutable caching (story 25). Storage IDs and filenames are never exposed.
         */
        get: operations["getArtImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maintenance/orphaned-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete orphaned image files and asset records
         * @description Operator-only maintenance endpoint with no frontend usage (see the project README's "Maintenance" section). Deletes cardImageAssets/ artImageAssets database rows that no card or art row references, along with their file(s), then deletes any remaining file in the local images directory with no asset row at all. Skips any asset row or file younger than 5 minutes so a request still in flight is never affected.
         */
        delete: operations["deleteOrphanedImages"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            status: "ok";
            /** @constant */
            database: "connected";
        };
        OrphanedImagesCleanupResult: {
            deletedFileCount: number;
            /** @description Filenames (not full paths) deleted from the local images directory. */
            deletedFiles: string[];
            /** @description Number of cardImageAssets/artImageAssets database rows deleted because no card or art row referenced them. */
            deletedAssetRecordCount: number;
        };
        ProblemDetails: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
        } & {
            [key: string]: unknown;
        };
        /** @description Centimeters, to two decimal places. Must be greater than zero. Used with widthBase to compute displayed width: (slots * widthPerSlot) + widthBase. */
        BinderWidthPerSlot: number;
        /** @description Centimeters, to two decimal places. May be negative only when the one-slot computed width (widthPerSlot + widthBase) remains greater than zero; the backend rejects combinations that don't. */
        BinderWidthBase: number;
        /** @description Centimeters, to two decimal places. Must be greater than zero. Used with heightBase to compute displayed height: (slots * heightPerSlot) + heightBase. */
        BinderHeightPerSlot: number;
        /** @description Centimeters, to two decimal places. May be negative only when the one-slot computed height (heightPerSlot + heightBase) remains greater than zero; the backend rejects combinations that don't. */
        BinderHeightBase: number;
        /** @description Six-digit `#RRGGBB` hexadecimal color. The backend normalizes hexadecimal letters to uppercase before saving. */
        BinderBorderColor: string;
        /** @description Percentage, to two decimal places, from 0 through 100 inclusive. */
        BinderBorderRadius: number;
        /** @description Centimeters, to two decimal places, zero or greater. Unlike BinderBorderRadius, this is a physical measurement rather than a percentage - the frontend converts it to pixels at render time using the same cm-to-px scale factor as the art's own image. */
        BinderBorderWidth: number;
        /** @description Story 20: one-based physical focal page resolved to the same single page or two-page spread as layout navigation. Must be between 1 and twice the binder's stored page count; the backend resets it to the shared DEFAULT_BINDER_PREVIEW_PHYSICAL_PAGE value when reducing the stored page count would otherwise make the saved value invalid. */
        BinderPreviewPhysicalPage: number;
        CreateBinderRequest: {
            /** @description Trimmed on the backend; case-insensitive uniqueness is enforced there. */
            name: string;
            /** @description Number of slot columns per binder side. */
            width: number;
            /** @description Number of slot rows per binder side. */
            height: number;
            /** @description Stored binder-page count. Physical pages range from 1 through 2 * pages. */
            pages: number;
            /** @description Defaults to the shared DEFAULT_WIDTH_PER_SLOT_CM value when omitted. */
            widthPerSlot?: components["schemas"]["BinderWidthPerSlot"];
            /** @description Defaults to the shared DEFAULT_WIDTH_BASE_CM value when omitted. */
            widthBase?: components["schemas"]["BinderWidthBase"];
            /** @description Defaults to the shared DEFAULT_HEIGHT_PER_SLOT_CM value when omitted. */
            heightPerSlot?: components["schemas"]["BinderHeightPerSlot"];
            /** @description Defaults to the shared DEFAULT_HEIGHT_BASE_CM value when omitted. */
            heightBase?: components["schemas"]["BinderHeightBase"];
            /** @description Defaults to the shared DEFAULT_BORDER_COLOR value when omitted. */
            borderColor?: components["schemas"]["BinderBorderColor"];
            /** @description Defaults to the shared DEFAULT_BORDER_RADIUS_PERCENT value when omitted. */
            borderRadius?: components["schemas"]["BinderBorderRadius"];
            /** @description Defaults to the shared DEFAULT_BORDER_WIDTH_CM value when omitted. */
            borderWidth?: components["schemas"]["BinderBorderWidth"];
            previewPhysicalPage?: components["schemas"]["BinderPreviewPhysicalPage"];
        };
        /** @description A partial update; only supplied fields are changed. Story 7 covers name/width/height/pages; story 24 adds the dimension and multi-slot-art style fields below; later stories add notes, preview page, and lock-state fields to this same request schema. */
        UpdateBinderRequest: {
            /** @description Trimmed on the backend; case-insensitive uniqueness is enforced there. */
            name?: string;
            /** @description Number of slot columns per binder side. */
            width?: number;
            /** @description Number of slot rows per binder side. */
            height?: number;
            /** @description Stored binder-page count. Physical pages range from 1 through 2 * pages. */
            pages?: number;
            widthPerSlot?: components["schemas"]["BinderWidthPerSlot"];
            widthBase?: components["schemas"]["BinderWidthBase"];
            heightPerSlot?: components["schemas"]["BinderHeightPerSlot"];
            heightBase?: components["schemas"]["BinderHeightBase"];
            borderColor?: components["schemas"]["BinderBorderColor"];
            borderRadius?: components["schemas"]["BinderBorderRadius"];
            borderWidth?: components["schemas"]["BinderBorderWidth"];
            previewPhysicalPage?: components["schemas"]["BinderPreviewPhysicalPage"];
        };
        /** @description `POST /binders/{binderId}/exports/pdf`'s request body (story 29). */
        ExportBinderPdfRequest: {
            /**
             * @description When true, renders each card's saved variation label below it in the generated PDF, mirroring the layout route's own `variations=true` toggle. The frontend sends `false` (or omits the field) whenever that toggle is off.
             * @default false
             */
            includeVariations: boolean;
        };
        /** @description `POST /binders/{binderId}/exports/art-pdf`'s request body (story 30) - the print-art selection modal's currently checked art ids. */
        ExportArtPdfRequest: {
            /** @description The ids of the binder's currently placed multi-slot art to include in the generated PDF. Every id must currently identify placed art in this binder; the array must not be empty. */
            selectedArtIds: string[];
        };
        Binder: {
            /** Format: uuid */
            id: string;
            name: string;
            width: number;
            height: number;
            pages: number;
            widthPerSlot: components["schemas"]["BinderWidthPerSlot"];
            widthBase: components["schemas"]["BinderWidthBase"];
            heightPerSlot: components["schemas"]["BinderHeightPerSlot"];
            heightBase: components["schemas"]["BinderHeightBase"];
            borderColor: components["schemas"]["BinderBorderColor"];
            borderRadius: components["schemas"]["BinderBorderRadius"];
            borderWidth: components["schemas"]["BinderBorderWidth"];
            previewPhysicalPage: components["schemas"]["BinderPreviewPhysicalPage"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description The lightweight binder representation used by the home-page binder list (story 5). Story 20 extends this schema with the dimension/ style fields (needed to render the embedded preview at the right proportions) and the embedded `preview` object itself, rather than the complete card and multi-slot-art graph. Story 22 may add completion-metric data the same way. */
        BinderSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            width: number;
            height: number;
            pages: number;
            widthPerSlot: components["schemas"]["BinderWidthPerSlot"];
            widthBase: components["schemas"]["BinderWidthBase"];
            heightPerSlot: components["schemas"]["BinderHeightPerSlot"];
            heightBase: components["schemas"]["BinderHeightBase"];
            borderColor: components["schemas"]["BinderBorderColor"];
            borderRadius: components["schemas"]["BinderBorderRadius"];
            borderWidth: components["schemas"]["BinderBorderWidth"];
            previewPhysicalPage: components["schemas"]["BinderPreviewPhysicalPage"];
            preview: components["schemas"]["BinderPreview"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Story 20: the single page or two-page spread `previewPhysicalPage` resolves to, matching layout navigation's own spread resolution. */
        BinderPreviewSpread: {
            left: number | null;
            right: number | null;
        };
        /** @description Story 20: one placed card within the preview spread - only the placement and image data the miniature layout needs to render it, excluding the card's own name/set/variation/source/timestamps. */
        BinderPreviewCard: {
            physicalPage: number;
            row: number;
            column: number;
            imageUrl: string;
        };
        /** @description Story 20: one placed multi-slot art item within the preview spread - only the placement, geometry, and image data the miniature layout needs to render it, excluding the art's own title/description/timestamps. */
        BinderPreviewArt: {
            physicalPage: number;
            row: number;
            column: number;
            widthSlots: number;
            heightSlots: number;
            imageUrl: string;
            imageRotationDegrees: number;
            focalX: number;
            focalY: number;
            scaleX: number;
            scaleY: number;
            borderColor: string | null;
            borderRadius: number | null;
            borderWidth: number | null;
        };
        /** @description Story 20: the binder's saved `previewPhysicalPage` resolved to a spread plus the cards and multi-slot art placed within it - the complete data the home-page preview needs to render, embedded directly in each `BinderSummary` so the home page issues no separate preview requests. */
        BinderPreview: {
            spread: components["schemas"]["BinderPreviewSpread"];
            cards: components["schemas"]["BinderPreviewCard"][];
            art: components["schemas"]["BinderPreviewArt"][];
        };
        /** @description One-based physical page, row, and column. All three are populated for a placed item and all three are null for an unplaced item (story 15's unplaced-cards section). */
        PlacementCoordinates: {
            physicalPage: number | null;
            row: number | null;
            column: number | null;
        };
        /** @description One card's expected current placement and its final placement (story 14), used within `MoveCardsRequest`. */
        CardPositionUpdate: {
            /** Format: uuid */
            cardId: string;
            expectedPlacement: components["schemas"]["PlacementCoordinates"];
            finalPlacement: components["schemas"]["PlacementCoordinates"];
        };
        /** @description `PATCH /cards/{cardId}`'s request body (story 14): one update for a simple move, or two updates - the dragged card and the destination's prior occupant - for a swap. */
        MoveCardsRequest: {
            updates: components["schemas"]["CardPositionUpdate"][];
        };
        /** @description `PATCH /cards/{cardId}`'s variation-update request body (story 16): replaces the path card's saved variation using last-write-wins semantics. Trimmed on the backend; a blank value is stored as `null`, and one value replaces the previous value. */
        UpdateCardVariationRequest: {
            variation: string | null;
        };
        /** @description A normalized TCGdex catalog card (story 11), returned by `GET /card-catalog/search` and submitted as-is (plus variation and placement) to create a TCGdex-sourced binder card. */
        TcgDexCatalogCard: {
            name: string;
            setName: string | null;
            localNumber: string | null;
            providerCardId: string;
            providerSetId: string;
            /**
             * Format: uri
             * @description The provider's image location; not the frontend-facing image URL.
             */
            imageUrl: string;
        };
        /**
         * @description Which TCGdex-language dataset a card-catalog search targets (story 41).
         * @enum {string}
         */
        CardSearchLanguage: "en" | "ja";
        /** @description `GET /card-catalog/search`'s response body (story 41). Wraps the normalized results with a nonblocking translation-warning flag instead of returning a bare array, so an unsuccessful English-to-Japanese translation attempt can be surfaced without an error response. */
        CardSearchResponse: {
            results: components["schemas"]["TcgDexCatalogCard"][];
            /** @description True only when `language=ja` and `query` looked like an English Pokémon species name attempt but no matching translation was found, so TCGdex was searched using the original entered query instead. */
            translationWarning: boolean;
        };
        /** @description Creates a TCGdex-sourced binder card (story 11). The backend does not refetch card details before saving; it assigns `source` server-side and downloads the image from `imageUrl` itself. */
        CreateCardRequest: {
            name: string;
            setName: string | null;
            localNumber: string | null;
            providerCardId: string;
            providerSetId: string;
            /** Format: uri */
            imageUrl: string;
            variation?: string | null;
            placement: components["schemas"]["PlacementCoordinates"];
        };
        /** @description Creates a manually-entered custom binder card via `multipart/ form-data` (story 12). The backend assigns `source: 'custom'` server-side, never accepts TCGdex identity fields, and computes a SHA-256 digest of the uploaded image while streaming it to temporary storage so identical uploads share one image asset. Placement is optional: supply `physicalPage`, `row`, and `column` together for a placed card, or omit all three for an unplaced card (story 15's unplaced-cards section) - supplying only some of the three is rejected. */
        CreateCustomCardRequest: {
            /** @description Trimmed and required after trimming on the backend. */
            name: string;
            /** @description Trimmed on the backend; a blank value is stored as null. */
            setName?: string;
            /** @description Trimmed on the backend; a blank value is stored as null. */
            localNumber?: string;
            /** @description Trimmed on the backend; a blank value is stored as null. */
            variation?: string;
            physicalPage?: number;
            row?: number;
            column?: number;
            /**
             * Format: binary
             * @description Required. Must be a JPEG, PNG, or WebP file; the backend validates the file's signature rather than trusting its name or multipart MIME type.
             */
            image: string;
        };
        /** @description The complete persisted representation of a binder-owned card. */
        Card: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            binderId: string;
            name: string;
            setName: string | null;
            localNumber: string | null;
            /** @enum {string} */
            source: "tcgdex" | "custom";
            providerCardId: string | null;
            providerSetId: string | null;
            variation: string | null;
            placement: components["schemas"]["PlacementCoordinates"];
            /**
             * Format: uri-reference
             * @description The backend's own `/cards/{cardId}/image` endpoint URL.
             */
            imageUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Creates multi-slot art via `multipart/form-data` (story 25). New art always starts in the unplaced-art section (all-null placement); the backend computes a SHA-256 digest of the uploaded image while streaming it to temporary storage so identical uploads share one art image asset, and uses `sharp` to inspect pixel dimensions and generate an EXIF-auto-oriented rendering derivative when needed. */
        CreateArtRequest: {
            /** @description Trimmed and required after trimming on the backend. */
            title: string;
            /** @description Trimmed on the backend; a blank value is stored as null. */
            description?: string;
            /** @description Must not exceed the binder's current width. */
            widthSlots: number;
            /** @description Must not exceed the binder's current height. */
            heightSlots: number;
            /**
             * @default 0
             * @enum {integer}
             */
            imageRotationDegrees: 0 | 90 | 180 | 270;
            /**
             * @description Normalized focal X coordinate relative to the computed centered-cover fit; rounded to 4 decimal places.
             * @default 0.5
             */
            focalX: number;
            /** @default 0.5 */
            focalY: number;
            /**
             * @description Horizontal scale multiplier relative to the centered-cover fit.
             * @default 1
             */
            scaleX: number;
            /** @default 1 */
            scaleY: number;
            /** @description Null uses the binder's current border color at render time. */
            borderColor?: string | null;
            /** @description Null uses the binder's current border radius at render time. */
            borderRadius?: number | null;
            /** @description Centimeters, to two decimal places, zero or greater. Null uses the binder's current border width at render time. */
            borderWidth?: number | null;
            /**
             * Format: binary
             * @description Required. Must be a JPEG, PNG, or WebP file; the backend validates the file's signature rather than trusting its name or multipart MIME type.
             */
            image: string;
        };
        /** @description The complete persisted representation of one multi-slot-art item. */
        Art: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            binderId: string;
            title: string;
            description: string | null;
            widthSlots: number;
            heightSlots: number;
            placement: components["schemas"]["PlacementCoordinates"];
            /**
             * Format: uri-reference
             * @description The backend's own `/art/{artId}/image` endpoint URL.
             */
            imageUrl: string;
            /** @enum {integer} */
            imageRotationDegrees: 0 | 90 | 180 | 270;
            focalX: number;
            focalY: number;
            scaleX: number;
            scaleY: number;
            borderColor: string | null;
            borderRadius: number | null;
            /** @description Centimeters, to two decimal places. Null means the binder's current border width applies at render time. */
            borderWidth: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description `PATCH /art/{artId}`'s `application/json` movement body (story 26). Unlike `MoveCardsRequest`, art never swaps - the destination is always for the one art item the path identifies - so this is a single expected/final placement pair rather than an array. */
        MoveArtRequest: {
            expectedPlacement: components["schemas"]["PlacementCoordinates"];
            finalPlacement: components["schemas"]["PlacementCoordinates"];
        };
        /** @description Edits an existing art item's metadata, transform, and style overrides via `multipart/form-data` (story 26), mirroring `CreateArtRequest`'s fields except that `image` is optional - omitting it keeps the art's current image. */
        UpdateArtRequest: {
            /** @description Trimmed and required after trimming on the backend. */
            title: string;
            /** @description Trimmed on the backend; a blank value is stored as null. */
            description?: string;
            /** @description Must not exceed the binder's current width. */
            widthSlots: number;
            /** @description Must not exceed the binder's current height. */
            heightSlots: number;
            /**
             * @default 0
             * @enum {integer}
             */
            imageRotationDegrees: 0 | 90 | 180 | 270;
            /** @default 0.5 */
            focalX: number;
            /** @default 0.5 */
            focalY: number;
            /** @default 1 */
            scaleX: number;
            /** @default 1 */
            scaleY: number;
            /** @description Null uses the binder's current border color at render time. */
            borderColor?: string | null;
            /** @description Null uses the binder's current border radius at render time. */
            borderRadius?: number | null;
            /** @description Centimeters, to two decimal places, zero or greater. Null uses the binder's current border width at render time. */
            borderWidth?: number | null;
            /**
             * @description When `true`, confirms saving even though the edited dimensions would leave currently-placed art out of bounds or overlapping another item; the art is moved to the unplaced-art section in the same request instead of returning `409 Conflict`.
             * @default false
             */
            moveToUnplacedOnConflict: boolean;
            /**
             * Format: binary
             * @description Optional. When supplied, must be a JPEG, PNG, or WebP file; the backend validates the file's signature rather than trusting its name or multipart MIME type. Omitting it keeps the art's current image.
             */
            image?: string;
        };
    };
    responses: never;
    parameters: {
        binderId: string;
        cardId: string;
        artId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and database are available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The database is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder-summary collection in its documented sort order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinderSummary"][];
                };
            };
        };
    };
    createBinder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBinderRequest"];
            };
        };
        responses: {
            /** @description The binder was created. */
            201: {
                headers: {
                    /** @description The path of the newly created binder resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The request body did not match the documented schema. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A binder with the same case-insensitively normalized name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getBinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteBinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder was deleted, or no binder existed with the given id. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateBinder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBinderRequest"];
            };
        };
        responses: {
            /** @description The complete persisted binder after applying the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Binder"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, or the request body did not match the documented schema. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A binder with the same case-insensitively normalized name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    duplicateBinder: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The duplicate binder's complete home-page binder summary. */
            201: {
                headers: {
                    /** @description The path of the newly created binder resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinderSummary"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, or the Idempotency-Key header is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    exportBinderLayoutPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportBinderPdfRequest"];
            };
        };
        responses: {
            /** @description The generated binder-layout PDF. */
            200: {
                headers: {
                    /** @description `attachment` with the sanitized binder name followed by `.pdf` as the suggested download filename. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, or the request body did not match the documented schema. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description PDF generation failed - for example, a placed card or art item's local image file is missing, unreadable, or not a supported format. No temporary file is left behind. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    exportArtPrintPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportArtPdfRequest"];
            };
        };
        responses: {
            /** @description The generated print-art PDF. */
            200: {
                headers: {
                    /** @description `attachment` with the sanitized binder name followed by `-art.pdf` as the suggested download filename. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, the request body did not match the documented schema, `selectedArtIds` was empty, or an id in `selectedArtIds` does not currently identify placed art in this binder. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description PDF generation failed - for example, a selected art item's local image file is missing, unreadable, or not a supported format. No temporary file is left behind. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinderCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder's cards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createBinderCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
                "multipart/form-data": components["schemas"]["CreateCustomCardRequest"];
            };
        };
        responses: {
            /** @description The card was created and placed. */
            201: {
                headers: {
                    /** @description The path of the newly created card resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, the request body did not match the documented schema, a placement partially (rather than fully) supplied its physical page, row, and column, or the supplied placement is not valid within the binder's current dimensions. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The target placement is already occupied by another card. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A custom card's uploaded file's signature did not match a supported image format (story 12). */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex image download failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex image download timed out. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    searchCardCatalog: {
        parameters: {
            query: {
                query: string;
                /** @description Defaults to `en` when omitted. For `ja`, the backend first attempts to translate `query` as an English Pokémon species name (see `CardSearchResponse.translationWarning`). */
                language?: components["schemas"]["CardSearchLanguage"];
                /** @description Defaults to `false` when omitted. When `false`, cards belonging to a Pokémon TCG Pocket set (TCGdex's `tcgp` serie) are excluded from results; when `true`, they're included alongside all other matches. */
                includeTcgPocket?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The normalized TCGdex search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSearchResponse"];
                };
            };
            /** @description The query is missing, or its trimmed length is below the configured minimum. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex search failed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The upstream TCGdex search timed out. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["cardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The card was deleted, or no card existed with the given id. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The cardId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["cardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCardsRequest"] | components["schemas"]["UpdateCardVariationRequest"];
            };
        };
        responses: {
            /** @description For a move/swap, the complete persisted representation of every card updated by the move or swap. For a variation update, the complete persisted representation of the path card. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][] | components["schemas"]["Card"];
                };
            };
            /** @description The cardId path parameter is not a well-formed UUID, the path cardId isn't included in `updates`, a placement is malformed or out of the binder's bounds, or the updates don't all belong to the same binder. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description One or more updates identify a card that doesn't exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An update's expected placement no longer matches the card's persisted placement, or the destination is occupied by a card not included in `updates`. No card positions are changed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCardImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["cardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The card's image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description The cardId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No card, image-asset record, or local file exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listBinderArt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The binder's multi-slot art. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Art"][];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    createBinderArt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                binderId: components["parameters"]["binderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateArtRequest"];
            };
        };
        responses: {
            /** @description The art was created in the unplaced-art section. */
            201: {
                headers: {
                    /** @description The path of the newly created art resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Art"];
                };
            };
            /** @description The binderId path parameter is not a well-formed UUID, the request body did not match the documented schema, or `widthSlots`/`heightSlots` exceed the binder's current width/height. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No binder exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The uploaded file's signature did not match a supported image format. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteArt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The art item was deleted, or no art existed with the given id. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The artId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    updateArt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveArtRequest"];
                "multipart/form-data": components["schemas"]["UpdateArtRequest"];
            };
        };
        responses: {
            /** @description The art item's complete persisted representation after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Art"];
                };
            };
            /** @description The artId path parameter is not a well-formed UUID, or the request body did not match the documented schema (a malformed placement, or metadata failing validation). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No art exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A move's expected placement no longer matches the art's persisted placement, the destination is occupied, or an edit's new dimensions would leave placed art out of bounds or overlapping another item without `moveToUnplacedOnConflict`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description A replacement image's signature did not match a supported image format. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    duplicateArt: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The duplicate art item, created in the unplaced-art section. */
            201: {
                headers: {
                    /** @description The path of the newly created art resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Art"];
                };
            };
            /** @description The artId path parameter is not a well-formed UUID, or the Idempotency-Key header is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No art exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getArtImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artId: components["parameters"]["artId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The art's image bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
            /** @description The artId path parameter is not a well-formed UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No art, image-asset record, or local file exists. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    deleteOrphanedImages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cleanup ran (even if there was nothing to delete). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrphanedImagesCleanupResult"];
                };
            };
        };
    };
}
